### ISSUE TITLE
Module not found

### ISSUE THREAD

**Issue by humrochagf** [kmonsoor/lektor-google-analytics#1]
When i try to install this plugin it gets a `ImportError: No module named lektor_google_analytics` error.
In order to get it instaled i changed the info on packages from:

```
[packages]
lektor-google-analytics = 0.1
```

to:

```
[packages]
lektor-google-analytics = 0.1.3
```

but it`s good for backward compatibility reasons keep a valid link to 0.1

**Comment by kmonsoor** [comment]
fixed by #2
